CRATE_NAME:=expr
BUILD_DIR:=build
SRC_DIR:=src
LIBS_DIR:=libs
DEBUG_LIBS_DIR:=$(LIBS_DIR)/debug
DEBUG_LIBRARY_LINKS:=$(DEBUG_LIBS_DIR)/libvec_buf.rlib
COMMON_RUSTC_FLAGS:=--edition=2024
DEBUG_BUILD_DIR:=$(BUILD_DIR)/debug
DEBUG_RUSTC_FLAGS:=$(COMMON_RUSTC_FLAGS) -L$(DEBUG_LIBS_DIR)
DEBUG_LIBRARY_RUSTC_FLAGS:=$(DEBUG_RUSTC_FLAGS) --out-dir=$(DEBUG_BUILD_DIR) --crate-type=lib --crate-name=$(CRATE_NAME)
DEBUG_LIBRARY_SRC_RS:=$(shell find $(SRC_DIR) -name \*.rs)
DEBUG_LIBRARY_TARGET:=$(DEBUG_BUILD_DIR)/lib$(CRATE_NAME).rlib
TEST_BUILD_DIR:=$(BUILD_DIR)/test
TEST_SRC_DIR:=test
TEST_RUSTC_FLAGS:=$(DEBUG_RUSTC_FLAGS) --out-dir=$(TEST_BUILD_DIR) -L$(DEBUG_BUILD_DIR)
TEST_TARGETS:=$(TEST_BUILD_DIR)/empty

.PHONY: all test clean
all: $(DEBUG_LIBRARY_TARGET)

$(DEBUG_LIBRARY_TARGET): $(DEBUG_SRC_RS) $(DEBUG_LIBRARY_LINKS)
	rustc $(DEBUG_LIBRARY_RUSTC_FLAGS) $(SRC_DIR)/lib.rs

$(TEST_TARGETS): $(TEST_BUILD_DIR)/%: $(TEST_SRC_DIR)/%.rs $(DEBUG_LIBRARY_TARGET) $(DEBUG_LIBRARY_LINKS)
	rustc $(TEST_RUSTC_FLAGS) $< && RUST_BACKTRACE=1 $@

test: $(TEST_TARGETS)

clean:
	rm -rf $(BUILD_DIR)
